export const ACTIONS = {
  SIGNUP_USER: 'set user',
  LOGIN_USER: 'login user',
  UPDATE_USER: 'update user',
  LOGOUT_USER: 'logout user',
  DELETE_USER: ' delete profile',
  GET_ALL_BOOKS: 'get all books',
  GET_POOL_OF_BOOKS: 'get pool of books',
  REMOVE_BOOK_FROM_POOL: 'remove book from pool',
  ADD_BOOK_TO_SAVED_BOOKS: 'add book to saved books',
  REMOVE_BOOK_FROM_SAVED_BOOKS: 'remove book from saved books',
  GET_SAVED_BOOKS: 'get saved books',
  GET_BOOKS_TO_OFFER: 'get books to offer',
  ADD_BOOK_TO_OFFERED_BOOKS: 'add book to offer',
  MARK_BOOK_AS_RESERVED: 'mark book as reserved',
  DELETE_BOOK: 'delete a book',
  GET_USERS_MATCHES: "get user's matches",
  CREATE_MATCH: 'create new match',
  UPDATE_MATCH: 'update match',
  DELETE_MATCH: 'delete match',
  DELETE_MULTIPLE_MATCHES: 'delete multiple matches',
  SET_TOKEN: 'set token',
  DELETE_TOKEN: 'delete token',
};
